macro (find_libcrypto)
    if(OPENSSL_STATIC_LINK)

        if(NOT OpenSSL_FOUND)
            set(OPENSSL_USE_STATIC_LIBS TRUE)
            find_package(OpenSSL REQUIRED)
            if(NOT OpenSSL_FOUND)
                message (FATAL_ERROR "static libcrypto not found. Aborting...")
            endif(NOT OpenSSL_FOUND)
        endif(NOT OpenSSL_FOUND)
        set(LIBCRYPTO_LDFLAGS OpenSSL::Crypto -ldl)
        if(VERBOSE_CMAKE)
            message("LIBCRYPTO_LDFLAGS: ${LIBCRYPTO_LDFLAGS}")
            message("OpenSSL_VERSION: ${OPENSSL_VERSION}")
        endif(VERBOSE_CMAKE)

    else(OPENSSL_STATIC_LINK)

        if(NOT LIBCRYPTO_FOUND)
            pkg_check_modules(LIBCRYPTO REQUIRED libcrypto)
            if(LIBCRYPTO_FOUND)
                if(VERBOSE_CMAKE)
                    message("LIBCRYPTO_FOUND: ${LIBCRYPTO_FOUND}")
                    message("LIBCRYPTO_LIBRARIES: ${LIBCRYPTO_LIBRARIES}")
                    message("LIBCRYPTO_LIBRARY_DIRS: ${LIBCRYPTO_LIBRARY_DIRS}")
                    message("LIBCRYPTO_LDFLAGS: ${LIBCRYPTO_LDFLAGS}")
                    message("LIBCRYPTO_LDFLAGS_OTHER: ${LIBCRYPTO_LDFLAGS_OTHER}")
                    message("LIBCRYPTO_INCLUDE_DIRS: ${LIBCRYPTO_INCLUDE_DIRS}")
                    message("LIBCRYPTO_CFLAGS: ${LIBCRYPTO_CFLAGS}")
                    message("LIBCRYPTO_CFLAGS_OTHER: ${LIBCRYPTO_CFLAGS_OTHER}")
                    message("LIBCRYPTO_VERSION: ${LIBCRYPTO_VERSION}")
                    message("LIBCRYPTO_INCLUDEDIR: ${LIBCRYPTO_INCLUDEDIR}")
                    message("LIBCRYPTO_LIBDIR: ${LIBCRYPTO_LIBDIR}")
                endif(VERBOSE_CMAKE)
            else(LIBCRYPTO_FOUND)
                message (FATAL_ERROR "libcrypto not found. Aborting...")
            endif(LIBCRYPTO_FOUND)
        endif(NOT LIBCRYPTO_FOUND)
        set(OPENSSL_VERSION ${LIBCRYPTO_VERSION})
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${LIBCRYPTO_CFLAGS}")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${LIBCRYPTO_CFLAGS}")
        link_directories(${LIBCRYPTO_LIBRARY_DIRS})

    endif(OPENSSL_STATIC_LINK)

endmacro()