== YKCS11
This is a PKCS#11 module that allows external applications to communicate with the PIV
application running on a YubiKey.

This module is based on version 2.40 of the PKCS#11 (Cryptoki) specifications. The complete specifications are available at
https://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html[oasis-open.org].

=== Building
YKCS11 is automatically built as part of `yubico-piv-tool` and the
following command will suffice:

  $ autoreconf --install
  $ ./configure
  $ make
  $ sudo make install

More info about building `yubico-piv-tool` can be found in the related
`README` file or in https://developers.yubico.com/yubico-piv-tool[yubico-piv-tool].

Once installed, the module will be found by default in
`/usr/local/lib/libykcs11.so` otherwise it will be built locally in
`yubico-piv-tool/ykcs11/.libs/libykcs11.so`

=== Portability
The module has been developed and tested using Ubuntu Linux and MacOS. It is however possible to cross-compile it for Windows too using the relative makefiles (windows.mk and mac.mk).
Both MacOS and Windows use PCSC as a backend.

==== Key Mapping
The module provides access to all 25 keys that can be stored on the YubiKey PIV application. These keys correspond to the keys in the PIV slots as described in https://developers.yubico.com/PIV/Introduction/Certificate_slots.html[PIV Certificate Slots] and are accessible through `yubico-piv-tool`.

The mapping is as follows:

[cols="2*^", options="header"]
|===
|ykcs11 id|PIV
|1|9a
|2|9c
|3|9d
|4|9e
|5 - 24 | 82 - 95
|25|f9
|===

==== Key Generation
Key pair generation is a particular operation, in the sense that
within PIV this is the only moment where the newly created public key
is given back to the user. To prevent the key from being lost, it is
automatically stored within the YubiKey by wrapping it in an X.509
certificate.

=== Attestation Certificates
Attestation certificates are also accessible with the YKCS11 module. An attestation certificate is a regular X509 Certificates that has the same `CKA_ID` and public key as the key it is attesting. Attestation certificates, however, are not stored in the YubiKey (`CKA_TOKEN` is FALSE) and are generated when accessed.

For more details about attestation, see the link:../Attestation.adoc[Attestation] section.

=== User Types
YKCS11 defines two types of users: a regular user and a security
officer (SO). These have been mapped to perform regular usage of the
private key material (PIN-associated operations) and device management
(management-key associated operations).

==== PINs and Management Key
The default user PIN for the YubiKey is `123456`. +
The default management key is
`010203040506070801020304050607080102030405060708`. +
All the YubiKey personalization (e.g. changing
management key, resetting PINs, resetting the application) is
currently done using `yubico-piv-tool`.

In order to perform operations involving the private keys, a regular
user must be logged in (i.e. using the PIN). However, given the
different PIN policies for different keys, subsequent operations might
require a new login. This is supported by the module through the `CONTEXT_SPECIFIC`
user in accordance with the specifications.

==== OpenSSL
The YubiKey only supports functions that require an asymmetrinc private key. Functions that do not, like encryption, signature verification, hashing and generation of a random number, are done by OpenSSL.

Also, the YubiKey only performs raw decryption and signature. So when padding is used, for example OAEP and PSS padding, applying and removing the padding is handled using OpenSSL functions.

==== Testing
Apart from the internal tests, the YKCS11 has also been tested with the Pkcs11Interop .NET library

==== Debugging
By default, the module has debugging disabled. This is _highly_ verbose
and might be confusing. In order to enabled it rebuild the project as
follows:

  $ autoreconf --install
  $ ./configure --enable-ykcs11-debug
  $ make
  $ sudo make install

It is also possible to use https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC[PKCS#11 Spy], as provided by OpenSC, to inspect the PKCS#11 communication.