name: MacOS Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      # This action checks-out the repository under $GITHUB_WORKSPACE, so the workflow can access it.
      - name: checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          set -x
          brew install pkg-config check gengetopt help2man opensc
      - name: run cmake
        run: |
          set -x
          mkdir cmake_build
          cd cmake_build
          cmake .. -DVERBOSE_CMAKE=ON -DOPENSSL_PKG_PATH=/usr/local/opt/openssl@1.1/lib/pkgconfig
          make
          make test

          otool -L tool/yubico-piv-tool | grep libcrypto
          otool -L lib/libykpiv.dylib | grep libcrypto
          otool -L ykcs11/libykcs11.dylib | grep libcrypto

          make install

          yubico-piv-tool --help | grep "Usage: yubico-piv-tool"
          objdump --syms /usr/local/lib/libykcs11.dylib | grep C_Sign
          pkcs11-tool --module /usr/local/lib/libykcs11.dylib --show-info | grep Yubico

      - name: Build using OpenSSL static link
        run: |
          set -x
          export PKG_CONFIG_PATH=/usr/local/opt/openssl@1.1/lib/pkgconfig:PKG_CONFIG_PATH

          rm -rf cmake_build; mkdir cmake_build; cd cmake_build
          cmake .. -DVERBOSE_CMAKE=ON -DOPENSSL_STATIC_LINK=ON -DBACKEND=macscard
          make
          make test

          otool -L tool/yubico-piv-tool | grep libcrypto | wc -l | grep 0
          otool -L lib/libykpiv.dylib | grep libcrypto | wc -l | grep 0
          otool -L ykcs11/libykcs11.dylib | grep libcrypto | wc -l | grep 0

          sudo make install

          yubico-piv-tool --help | grep "Usage: yubico-piv-tool"

          pkcs11-tool --module /usr/local/lib/libykcs11.dylib --show-info | grep Yubico